version: 2
updates:
- package-ecosystem: "yarn"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 5
  reviewers:
  - "nileshpawarr"
  assignees:
  - "nileshpawarr"
  labels:
  - "Status: Review Needed"
  - "Size: S"
  - "dependencies"
  pull-request-branch-name:
    separator: "-"
